### ISSUE TITLE
Main Image for Readme

### ISSUE THREAD

**Issue by omid3098** [ElectroGryphon/EGGA#1]
![inputfield](https://cloud.githubusercontent.com/assets/19928031/16045524/05988ed8-325e-11e6-8be9-f919321def01.gif)

**Comment by omid3098** [comment]
![bestfit](https://cloud.githubusercontent.com/assets/19928031/16045806/5e3c93e4-325f-11e6-9bab-9242df7c225b.gif)

**Comment by ElectroGryphon** [comment]
![rightclickcontextmenu](https://cloud.githubusercontent.com/assets/19928031/16046308/371c261a-3261-11e6-83ee-2864cbffb57b.gif)
