### ISSUE TITLE
Handling multiple periods with English text only

### ISSUE THREAD

**Issue by codedrunk** [ElectroGryphon/EGGA#10]
If you write English text only and put multiple periods at the end, all but one periods start going to the left.

Sample input: "sample...."
Output: "...sample."

**Comment by omid3098** [comment]
If you just want to write English text, you can just set RtlText.active = false;

**Comment by codedrunk** [comment]
Fair enough

**Comment by omid3098** [comment]
When you use both RTL and English text in a same sentence, it's hard to detect those dots '...' are suppose to consider as RTL or English.
