### ISSUE TITLE
Remove or convert `zwnj` charachter

### ISSUE THREAD

**Issue by masudafsar** [ElectroGryphon/EGGA#11]
hi,

When I use [zwnj](https://en.wikipedia.org/wiki/Zero-width_non-joiner) char in the text, like this `سکه‌ها` script convert or remove `zwnj` and show that like `سکهها`.

Are any idea to fix it?

**Comment by Enzx** [comment]
Hey @masudafsar  
Thank you for pointing out the issue. It's come from Bidi-Text algorithm (https://tools.ietf.org/html/rfc1556)  implementation. We're using ArabicSupport plugin. Also, I've tested Nbidi which is the same implementation and the same problem exist there too. You have to modify ArabicSupport source code to fix the issue. You have to change the character before and after 'zwnj' character like the space character.
