### ISSUE TITLE
The referenced script on this Behaviour is missing!

### ISSUE THREAD

**Issue by arshamnm** [ElectroGryphon/EGGA#12]
Currently, the EGG script will cause the error:  
`The referenced script on this Behaviour (Game Object 'text') is missing!`  
because of the wrong place of directives.  
Modify the code to:  
`using UnityEditor;
using UnityEngine;
namespace UPersian.Scripts
{
    [ExecuteInEditMode]
    public class EGG : MonoBehaviour
    {
         #if UNITY_EDITOR
             .. the remaining code ..
         #endif
    }
}
`  
or add:  
`#else
    using UnityEngine;
    namespace UPersian.Scripts
    {
        public class EGG : MonoBehaviour
        {}
    }`
right before `#endif`
to avoid such error

**Comment by omid3098** [comment]
Thank you @arshamnm 
It would be great if you send a PR on this case and I will gladly check and merge it.

**Comment by arshamnm** [comment]
Don't mention it
Sure :)
I was in a rush at that time
There you are...

**Comment by omid3098** [comment]
Thanks for the PR. ✌️
Merged
