### ISSUE TITLE
There is no canvas error

### ISSUE THREAD

**Issue by Meshkati** [ElectroGryphon/EGGA#5]
Hi! When I'm tring to add a new RTL Text, I get this error:

> There is no Canvas
UnityEngine.Debug:Log(Object)
UPersian.Editor.UPersianContext:FindCorrectParent() (at Assets/EGGA/UPersian/Scripts/Editor/UPersianContext.cs:101)
UPersian.Editor.UPersianContext:CreateRtlToggle() (at Assets/EGGA/UPersian/Scripts/Editor/UPersianContext.cs:80)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32)

**Comment by omid3098** [comment]
Hi, you should add a canvas in your scene first. RTL objects look for canvas and use them as the parent.
