### ISSUE TITLE
Adding an option to enable/disable RTL Fixing in RTL Text prefab

### ISSUE THREAD

**Issue by amsonline** [ElectroGryphon/EGGA#9]
When I want to put English text inside RTLText prefab, it messes up the text, specially if it has some characters like , { } ( ).
I want to use this Game object on multi-language project, and it would be very nice to add something like a checkbox to enable/disable RTLFixing, so the Game Object works like normal Text object if we disable it.

**Comment by omid3098** [comment]
Fixed in this commit dd1251a.
If you want to active/deactivate rtl formatting in inspector, use inspector debug mode.
if you want to use it in code, just set RtlText.active = false; or true whenever you need.
